# Generated by Django 5.2.16 on 2026-08-01 15:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='软删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('account_type', models.CharField(choices=[('cash', '现金'), ('bank', '银行卡'), ('credit', '信用卡'), ('wallet', '数字钱包'), ('investment', '投资账户'), ('other', '其他')], default='bank', max_length=16, verbose_name='类型')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='币种')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='期初余额')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ledgers.ledger')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='软删除时间')),
                ('kind', models.CharField(choices=[('expense', '支出'), ('income', '收入')], default='expense', max_length=8, verbose_name='类型')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('icon', models.CharField(blank=True, default='', max_length=16, verbose_name='图标')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ledgers.ledger')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='transactions.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['kind', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('budget_type', models.CharField(choices=[('total', '账本总支出'), ('category', '分类支出'), ('top_category', '一级分类支出')], default='category', max_length=16, verbose_name='类型')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份')),
                ('month', models.PositiveSmallIntegerField(verbose_name='月份')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='预算金额')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='ledgers.ledger')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='transactions.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '预算',
                'verbose_name_plural': '预算',
                'ordering': ['-year', '-month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('color', models.CharField(blank=True, default='', max_length=16, verbose_name='颜色')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ledgers.ledger')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='软删除时间')),
                ('type', models.CharField(choices=[('expense', '支出'), ('income', '收入'), ('transfer', '转账'), ('adjustment', '调整')], max_length=16, verbose_name='类型')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='原币币种')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, verbose_name='汇率')),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='基础币金额')),
                ('counterparty', models.CharField(blank=True, max_length=128, verbose_name='交易对象')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.category', verbose_name='分类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing', to='transactions.account', verbose_name='来源账户')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledgers.ledger')),
                ('tags', models.ManyToManyField(blank=True, related_name='transactions', to='transactions.tag')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='transactions.account', verbose_name='目标账户')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '流水',
                'verbose_name_plural': '流水',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='拆分金额')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='transactions.category', verbose_name='分类')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='transactions.transaction')),
            ],
            options={
                'verbose_name': '流水拆分',
                'verbose_name_plural': '流水拆分',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['ledger', 'is_active'], name='transaction_ledger__a5aa83_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('ledger', 'name'), name='uniq_account_ledger_name'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['ledger', 'kind', 'is_active'], name='transaction_ledger__e7f870_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('ledger', 'kind', 'name'), name='uniq_category_ledger_kind_name'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('ledger', 'budget_type', 'category', 'year', 'month'), name='uniq_budget_scope'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('ledger', 'name'), name='uniq_tag_ledger_name'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ledger', 'date'], name='transaction_ledger__cb13fc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ledger', 'type', 'date'], name='transaction_ledger__340bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ledger', 'from_account'], name='transaction_ledger__9144d0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ledger', 'to_account'], name='transaction_ledger__dc2a40_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ledger', 'category'], name='transaction_ledger__3ad14e_idx'),
        ),
    ]
