# Generated by Django 5.2.16 on 2026-08-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('expense', '支出'), ('income', '收入'), ('transfer', '转账'), ('adjustment', '调整'), ('refund', '退款'), ('reimbursement', '报销')], max_length=16, verbose_name='类型'),
        ),
    ]
