# Generated by Django 5.2.16 on 2026-08-01 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('report_type', models.CharField(default='custom', max_length=16, verbose_name='报表类型')),
                ('definition_json', models.JSONField(default=dict, verbose_name='定义')),
                ('is_shared', models.BooleanField(default=True, verbose_name='共享给成员')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_definitions', to='ledgers.ledger')),
            ],
            options={
                'verbose_name': '报表定义',
                'verbose_name_plural': '报表定义',
                'ordering': ['-updated_at'],
            },
        ),
    ]
