# Generated by Django 5.2.16 on 2026-08-01 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('delete', '删除'), ('restore', '恢复'), ('member_add', '添加成员'), ('member_remove', '移除成员'), ('member_role', '变更角色'), ('owner_transfer', '转移所有权'), ('ledger_update', '账本设置'), ('import', '数据导入'), ('export', '数据导出'), ('bulk', '批量操作'), ('other', '其他')], max_length=24, verbose_name='操作')),
                ('object_type', models.CharField(blank=True, max_length=32, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, max_length=32, verbose_name='对象 ID')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='摘要')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='变更内容')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ledgers.ledger')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ledger', '-created_at'], name='audit_audit_ledger__06e106_idx'), models.Index(fields=['ledger', 'object_type', 'object_id'], name='audit_audit_ledger__eb9e18_idx')],
            },
        ),
    ]
