# Generated by Django 5.2.16 on 2026-08-01 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='软删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('base_currency', models.CharField(default='CNY', max_length=8, verbose_name='基础货币')),
                ('timezone', models.CharField(default='Asia/Taipei', max_length=64, verbose_name='时区')),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, verbose_name='财年起始月份')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_ledgers', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '账本',
                'verbose_name_plural': '账本',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('target_username', models.CharField(blank=True, max_length=64, verbose_name='目标用户名')),
                ('target_email', models.EmailField(blank=True, max_length=254, verbose_name='目标邮箱')),
                ('role', models.PositiveSmallIntegerField(choices=[(10, '所有者'), (20, '管理员'), (30, '编辑者'), (40, '只读')], default=30, verbose_name='默认角色')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='令牌')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接受时间')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='接受人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='ledgers.ledger')),
            ],
            options={
                'verbose_name': '账本邀请',
                'verbose_name_plural': '账本邀请',
            },
        ),
        migrations.CreateModel(
            name='LedgerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.PositiveSmallIntegerField(choices=[(10, '所有者'), (20, '管理员'), (30, '编辑者'), (40, '只读')], default=30, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ledgers.ledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '账本成员',
                'verbose_name_plural': '账本成员',
            },
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['owner', 'archived_at'], name='ledgers_led_owner_i_389fec_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerinvitation',
            index=models.Index(fields=['token'], name='ledgers_led_token_8a7792_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgermembership',
            index=models.Index(fields=['user', 'is_active'], name='ledgers_led_user_id_feef80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ledgermembership',
            unique_together={('ledger', 'user')},
        ),
    ]
